apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-provider-frontend
  namespace: oc-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-provider-frontend
  template:
    metadata:
      labels:
        app: oc-provider-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
